import { NavBar } from '@/components/NavBar';
import './globals.css';
import { CartProvider } from './store/cart-context';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-w-full p-0 m-0">
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
