import './globals.css';
import Header from '@/components/Header';
import Modal from '@/components/UI/Modal';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-w-[350px] overflow-scroll">
        <Header />
        {children}
      </body>
    </html>
  );
}
